Quest2/Models/Bookings.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Quest2.Models
{
    public class Bookings
    {
        public int BookingId { get; set; }

        public string Name { get; set; }
        
        //[Required, Phone, Display(Name = "Phone number")]
        [Required(ErrorMessage = "You must provide a Mobile number")]
        [Display(Name = "Mobile")]
        [DataType(DataType.PhoneNumber)]
        public string Mobile { get; set; }

        public int TreatmentId { get; set; }

        public int TimeSlotId { get; set; }

        public string Note { get; set; }

        [Required]
        [RegularExpression("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9]+)*\\.([a-z]{2,4})$", ErrorMessage = "Invalid email format.")]
        //[EmailAddress(ErrorMessage ="Invalid Email Format")]
        public string Email { get; set; }

        [Required, DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime BookedDate { get; set; }

        public bool IsDeleted { get; set; }

        public  LU_TimeSlot TimeSlots { get; set; }

        public  LU_Treatment Treatments { get; set; }
        
    }
}

Quest2/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Quest2.Models;
using Quest2.ViewModels;

namespace Quest2.Controllers
{
    // [Route("api/[Controller]")]
    [EnableCors("AllowAnyOrigin")]
    public class BookingController : Controller
    {
        private AppDbContext _appDbContext;

        private readonly IBookingsRepository _bookingRepositor;
        private readonly ITimeSlotRepository _timeSlotRepository;
        private readonly ITreatmentRepository _treatmentRepository;


        // Constractor 
        public BookingController(IBookingsRepository bookingsRepository, ITimeSlotRepository timeSlotRepository, ITreatmentRepository treatmentRepository, AppDbContext appDbContext)
        {
            _bookingRepositor = bookingsRepository;
            _timeSlotRepository = timeSlotRepository;
            _treatmentRepository = treatmentRepository;
            _appDbContext = appDbContext;
        }
      
        //................................................
        //Get All Bookings controller:{Booking}/action:{List1}
        public IActionResult List1()
        {
            var bookings = _bookingRepositor.GetAllBookings().OrderBy(p => p.Name);

            foreach (var b in bookings)
            {
                b.TimeSlots = _appDbContext.TimeSlots.Single(t => t.TimeSlotId == b.TimeSlotId);
                b.Treatments = _appDbContext.Treatments.Single(t => t.TreatmentId == b.TreatmentId);

            }
            return View(bookings);
        }
        //................................................
        //Get  Bookings By Name 
        public IActionResult Index(string searchString)
        {
            var bookings = _bookingRepositor.GetBookingsByName(searchString);
            foreach (var b in bookings)
            {
                b.TimeSlots = _appDbContext.TimeSlots.Single(t => t.TimeSlotId == b.TimeSlotId);
                b.Treatments = _appDbContext.Treatments.Single(t => t.TreatmentId == b.TreatmentId);
            }
            bookings = bookings.ToList();
            
            return View(bookings);
        }
        //................................................
        //Get  Bookings By  Mobile Number
        public IActionResult Index2(string searchNum)
        {
            var bookings = _bookingRepositor.GetBookingsByNumber(searchNum);
            foreach (var b in bookings)
            {
                b.TimeSlots = _appDbContext.TimeSlots.Single(t => t.TimeSlotId == b.TimeSlotId);
                b.Treatments = _appDbContext.Treatments.Single(t => t.TreatmentId == b.TreatmentId);
            }
            bookings = bookings.ToList();

            return View(bookings);
        }
        //GetBookingsByNameMobile
        //................................................
        //Get  Bookings By Name && Mobile Number
        public IActionResult IndexBoth(string searchString, string searchNum)
        {
            var bookings = _bookingRepositor.GetBookingsByNameMobile(searchString, searchNum);
            foreach (var b in bookings)
            {
                b.TimeSlots = _appDbContext.TimeSlots.Single(t => t.TimeSlotId == b.TimeSlotId);
                b.Treatments = _appDbContext.Treatments.Single(t => t.TreatmentId == b.TreatmentId);
            }
            bookings = bookings.ToList();

            return View(bookings);
        }
        //............................................  
        //Get Details
        public IActionResult Details(int id)
        {
            var booking = _bookingRepositor.GetBookingsById(id);
            if (booking == null)
                return NotFound();
            
            booking.TimeSlots = _appDbContext.TimeSlots.Single(t => t.TimeSlotId == booking.TimeSlotId);
            booking.Treatments = _appDbContext.Treatments.Single(t => t.TreatmentId == booking.TreatmentId);
 
            return View(booking);
        }

        //............................................  
        // Get Create  controller:{Booking}/action:{Create}
        [HttpGet]
        public IActionResult Create()
        {
            List<LU_TimeSlot> li = new List<LU_TimeSlot>();
            List<LU_Treatment> lii = new List<LU_Treatment>();
            li = _appDbContext.TimeSlots.ToList();
            lii = _appDbContext.Treatments.ToList();
            ViewBag.listOfItems = li;
            ViewBag.listOfTreatment = lii;

            return View();
        }
        //............................................  
        // Post Create  controller:{Booking}/action:{Create}
        [HttpPost]
        public IActionResult Create(Bookings booking)
        {
            //if (ModelState.IsValid)
            //{
                _bookingRepositor.AddBookings(booking);
                return RedirectToAction("List1");
            //}
           // return View(booking);
        }
        //............................................    
        //Delete Booking By Id
        public IActionResult Delete(int id)
        {
            _bookingRepositor.DeleteBooking(id);
           
            return RedirectToAction("List1");
        }

        //............................................
        // Get Edit  controller:{Booking}/action:{Edit}
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Bookings bookings = _bookingRepositor.GetBookingsById(Id);

            List<LU_TimeSlot> li = new List<LU_TimeSlot>();
            List<LU_Treatment> lii = new List<LU_Treatment>();
            li = _appDbContext.TimeSlots.ToList();
            lii = _appDbContext.Treatments.ToList();
            ViewBag.listOfItems = li;
            ViewBag.listOfTreatment = lii;

            return View("Edit" ,bookings);
        }
        //................................................
        // Post Edit  
        [HttpPost]
        public IActionResult Edit( int Id,Bookings booking)
        {
            Console.WriteLine("............Jsone....1.....");
            Console.WriteLine(JsonConvert.SerializeObject(booking));
            // Console.WriteLine(JObject.Parse(booking.Name));
            Console.WriteLine("............Jsone....2.....");
            _bookingRepositor.UpdateBooking(Id,booking);
             
            return RedirectToAction("List1");
        }
    }
}


//................................................
//Get All Bookings 
//public IActionResult List()
//{
//    var bookings = _bookingRepositor.GetAllBookings().OrderBy(p => p.Name);
//    var bookingListViewModel = new BookingListViewModel()
//    {
//        Bookingss = bookings.ToList(),
//    };

//    return View(bookingListViewModel);
//}
//public ActionResult Delete(int? id)
//{
//    if (id != null)
//    {
//        var data = (from Bookings in _appDbContext.Bookingss
//                    where Bookings.BookingId == id
//                    select Bookings).SingleOrDefault();

//        _appDbContext.Remove(data);
//        _appDbContext.SaveChanges();
//    }
//    return RedirectToPage("List");
//}
//.........................................................
//public async Task<IActionResult> Details(int? id)
//{
//    if (id == null)
//    {
//        return NotFound();
//    }

//    var booking = await _appDbContext.Bookingss
//        .Include(b => b.TimeSlots)
//        .SingleOrDefaultAsync(m => m.BookingId == id);

//    if (booking == null)
//    {
//        return NotFound();
//    }

//    return View(booking);
//}
//............................................
//public ViewResult List()
//{
//    BookingListViewModel bookingListViewModel = new BookingListViewModel();
//    bookingListViewModel.Bookingss = _bookingRepositor.Bookings;

//    bookingListViewModel.TreatmentTitle = "treatment 1";
//    bookingListViewModel.TimeSlotTitle = 1;
//    return View(bookingListViewModel);
//}

//..................................................
//// Return All Bookings as array of objects 
//public JsonResult GetAll()
//{
//    var temp = new JsonResult(_bookingRepositor.GetAllBookings().OrderBy(p => p.Name));
//    temp.StatusCode = 200;

//    //foreach (var b in temp)
//    //{
//    //    b.TimeSlots = _appDbContext.TimeSlots.Single(t => t.TimeSlotId == b.TimeSlotId);
//    //    b.Treatments = _appDbContext.Treatments.Single(t => t.TreatmentId == b.TreatmentId);

//    //}
//    return temp;
//}

Quest2/Views/Booking/Create.cshtml
@model Bookings

 <div  >  
     <form method="Post" class="form-horizontal" role="form">


         <br>
         <br>
         <br>
         <div class="form-group">
             <label asp-for="Name" class="col-md-4 control-label"></label>
             <div class="col-md-5">
                 <input asp-for="Name" />
             </div>
         </div>

         <div class="form-group">
             <label asp-for="Email" class="col-md-4 control-label"></label>
             <div class="col-md-5">
                 <input asp-for="Email" type="email" />
                 <span asp-validation-for="Email" class="text-danger"></span>

             </div>
         </div>

         <div class="form-group">
             <label asp-for="Mobile" class="col-md-4 control-label"></label>
             <div class="col-md-5">
                 <input asp-for="Mobile" />
                 <span asp-validation-for="Mobile" class="text-danger"></span>

             </div>
         </div>

         <div class="form-group">
             <label asp-for="Note" class="col-md-4 control-label"></label>
             <div class="col-md-5">
                 <textarea asp-for="Note"></textarea>

             </div>
         </div>

        

         <div class="form-group">
             <label asp-for="BookedDate" class="col-md-4 control-label"></label>
             <div class="col-md-5">
                 <input asp-for="BookedDate" />

             </div>
         </div>

         <div class="form-group">
             <label asp-for="Treatments.TreatmentTitle" class="col-md-4 control-label"></label>
             <div class="col-md-5">
                 <select asp-for="TreatmentId" asp-items="@(new SelectList(@ViewBag.listOfTreatment,"TreatmentId","TreatmentTitle"))"></select>


             </div>
         </div>
         <div class="form-group">
             <label asp-for="TimeSlots.TimeSlotTitle" class="col-md-4 control-label"></label>
             <div class="col-md-5">
                 <select asp-for="TimeSlotId" asp-items="@(new SelectList(@ViewBag.listOfItems,"TimeSlotId","TimeSlotTitle"))"></select>


             </div>
         </div>


         <div class="form-group">
             <div class="col-md-offset-2 col-md-5">
                 <input type="submit" class="btn btn-primary" value="Book" />
             </div>
         </div>

     </form>
</div>

Quest2/Views/Booking/Details.cshtml
@model Bookings
    
<div class="container">
    <br>
    <br>
    <br>
    <h1> Details of Booking </h1>
    <h2>@Model.Name</h2>
</div>
   <div class="container">
       <div class="thumbnail">
           <div class="caption-full">


               <div class="form-group">
                   <label asp-for="@Model.TimeSlots.TimeSlotTitle" class="col-md-7 control-label"></label>
                   <div class="col-md-5">
                       @Model.TimeSlots.TimeSlotTitle
                   </div>
                   <br>
               </div>

               <div class="form-group">
                   <label asp-for="@Model.Treatments.TreatmentTitle" class="col-md-7 control-label"></label>
                   <div class="col-md-5">
                       @Model.Treatments.TreatmentTitle
                   </div>
                   <br>
               </div>

               <div class="form-group">
                   <label asp-for="@Model.Mobile" class="col-md-7 control-label"></label>
                   <div class="col-md-5">
                       @Model.Mobile
                   </div>
                   <br>
               </div>

               <div class="form-group">
                   <label asp-for="@Model.Email" class="col-md-7 control-label"></label>
                   <div class="col-md-5">
                       @Model.Email
                   </div>
                   <br>
               </div>

               <div class="form-group">
                   <label asp-for="@Model.IsDeleted" class="col-md-7 control-label"></label>
                   <div class="col-md-5">
                       @Model.IsDeleted
                   </div>
                   <br>
               </div>

               <div class="form-group">
                   <label asp-for="@Model.Note" class="col-md-7 control-label"></label>
                   <div class="col-md-5">
                       @Model.Note
                   </div>
                   <br>
               </div>

               <div class="form-group">
                   
                   <div class="col-md-5">
                       <a class="btn btn-warning" style="text-decoration:none" asp-controller="Booking" asp-action="List1">
                           Back
                       </a>
                   </div>
                   <br>
               </div>


               
           </div>
          </div>
 </div>

Quest2/Views/Booking/Edit.cshtml
@model Bookings

<div>
    <form method="Post" class="form-horizontal" role="form">


        <br>
        <br>
        <br>
        <div class="form-group">
            <label asp-for="Name" class="col-md-4 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Name"  readonly/>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Email" class="col-md-4 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Email" type="email"  readonly/>

            </div>
        </div>

        <div class="form-group">
            <label asp-for="Mobile" class="col-md-4 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Mobile"   readonly/>

            </div>
        </div>

        <div class="form-group">
            <label asp-for="Note" class="col-md-4 control-label"></label>
            <div class="col-md-5">
                <textarea asp-for="Note"></textarea>

            </div>
        </div>

        

        <div class="form-group">
            <label asp-for="BookedDate" class="col-md-4 control-label"></label>
            <div class="col-md-5">
                <input asp-for="BookedDate" />

            </div>
        </div>

        <div class="form-group">
            <label asp-for="Treatments.TreatmentTitle" class="col-md-4 control-label"></label>
            <div class="col-md-5">
                <select asp-for="TreatmentId" asp-items="@(new SelectList(@ViewBag.listOfTreatment,"TreatmentId","TreatmentTitle"))"></select>


            </div>
        </div>
        <div class="form-group">
            <label asp-for="TimeSlots.TimeSlotTitle" class="col-md-4 control-label"></label>
            <div class="col-md-5">
                <select asp-for="TimeSlotId" asp-items="@(new SelectList(@ViewBag.listOfItems,"TimeSlotId","TimeSlotTitle"))"></select>
            </div>

        </div>

        <div class="form-group">
                    <div class="col-md-offset-2 col-md-5">
                        <table>
                            <tr>
                                <td>
                                    <input type="submit" class="btn btn-primary" value="Update" />

                                </td>
                                <td></td>
                                <td>
                                    <a class="btn btn-warning" style="text-decoration:none" asp-controller="Booking" asp-action="List1">
                                        Cancel
                                    </a>
                                </td>
                            </tr>

                        </table>
                       
                    </div>
                </div>


    </form>
</div>

Quest2/Views/Booking/Index.cshtml
@model IEnumerable<Bookings>

@{
    Layout = "_Layout";
}

<div class="container" style="margin-top:6%">

    <h1>Bookings</h1>
    <hr />
</div>



<form asp-controller="Bookings" asp-action="Index" method="post">
    
            <a asp-controller="Booking" asp-action="List1">Back to Full List</a>
       
</form>


<table class="table">
    <thead>

        <tr>
            <th>Name</th>
            <th>Mobile</th>
            <th>Date</th>
            <th>TimeSlotTitle</th>
            <th>TreatmentTitle</th>
            <th>IsDeleted</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var bookings in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Booking" asp-action="Details" asp-route-id="@bookings.BookingId"> @bookings.Name</a>

                </td>
                <td>
                    @bookings.Mobile

                </td>
                <td>
                    @bookings.BookedDate.Date.ToShortDateString()
                </td>
                <td>
                    @bookings.TimeSlots.TimeSlotTitle

                </td>
                <td>
                    @bookings.Treatments.TreatmentTitle
                </td>
                <td>
                    @bookings.IsDeleted
                </td>
                <td>
                    <a asp-controller="Booking" asp-action="Edit" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-primary" value="Edit" />

                        <i class="glyphicon glyphicon-pencil"></i>

                    </a>

                </td>

                <td>
                    <a asp-controller="Booking" asp-action="Details" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-info" value="Details" />
                        <i class="glyphicon glyphicon-user"></i>

                    </a>
                </td>

                <td>
                    <a asp-controller="Booking" asp-action="Delete" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-danger" value="Delete" />
                        <i class="glyphicon glyphicon-trash"></i>

                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Quest2/Views/Booking/Index2.cshtml
@model IEnumerable<Bookings>

@{
    Layout = "_Layout";
}

<div class="container" style="margin-top:6%">

    <h1>Bookings</h1>
    <hr />
</div>



<form asp-controller="Bookings" asp-action="Index2" method="post">

    <a asp-controller="Booking" asp-action="List1">Back to Full List</a>

</form>


<table class="table">
    <thead>

        <tr>
            <th>Name</th>
            <th>Mobile</th>
            <th>Date</th>
            <th>TimeSlotTitle</th>
            <th>TreatmentTitle</th>
            <th>IsDeleted</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var bookings in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Booking" asp-action="Details" asp-route-id="@bookings.BookingId"> @bookings.Name</a>

                </td>
                <td>
                    @bookings.Mobile

                </td>
                <td>
                    @bookings.BookedDate.Date.ToShortDateString()
                </td>
                <td>
                    @bookings.TimeSlots.TimeSlotTitle

                </td>
                <td>
                    @bookings.Treatments.TreatmentTitle
                </td>
                <td>
                    @bookings.IsDeleted
                </td>
                <td>
                    <a asp-controller="Booking" asp-action="Edit" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-primary" value="Edit" />

                        <i class="glyphicon glyphicon-pencil"></i>

                    </a>

                </td>

                <td>
                    <a asp-controller="Booking" asp-action="Details" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-info" value="Details" />
                        <i class="glyphicon glyphicon-user"></i>

                    </a>
                </td>

                <td>
                    <a asp-controller="Booking" asp-action="Delete" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-danger" value="Delete" />
                        <i class="glyphicon glyphicon-trash"></i>

                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Quest2/Views/Booking/IndexBoth.cshtml
@model IEnumerable<Bookings>

@{
    Layout = "_Layout";
}

<div class="container" style="margin-top:6%">

    <h1>Bookings</h1>
    <hr />
</div>



<form asp-controller="Bookings" asp-action="IndexBoth" method="post">

    <a asp-controller="Booking" asp-action="List1">Back to Full List</a>

</form>


<table class="table">
    <thead>

        <tr>
            <th>Name</th>
            <th>Mobile</th>
            <th>Date</th>
            <th>TimeSlotTitle</th>
            <th>TreatmentTitle</th>
            <th>IsDeleted</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var bookings in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Booking" asp-action="Details" asp-route-id="@bookings.BookingId"> @bookings.Name</a>

                </td>
                <td>
                    @bookings.Mobile

                </td>
                <td>
                    @bookings.BookedDate.Date.ToShortDateString()
                </td>
                <td>
                    @bookings.TimeSlots.TimeSlotTitle

                </td>
                <td>
                    @bookings.Treatments.TreatmentTitle
                </td>
                <td>
                    @bookings.IsDeleted
                </td>
                <td>
                    <a asp-controller="Booking" asp-action="Edit" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-primary" value="Edit" />

                        <i class="glyphicon glyphicon-pencil"></i>

                    </a>

                </td>

                <td>
                    <a asp-controller="Booking" asp-action="Details" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-info" value="Details" />
                        <i class="glyphicon glyphicon-user"></i>

                    </a>
                </td>

                <td>
                    <a asp-controller="Booking" asp-action="Delete" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-danger" value="Delete" />
                        <i class="glyphicon glyphicon-trash"></i>

                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Quest2/Views/Booking/List1.cshtml
@model IEnumerable<Bookings>

@{
    Layout = "_Layout";
}

<div class="container" style="margin-top:6%">

    <h1>Bookings</h1>
    <hr />
</div>



<form>
    <div class="form-actions no-color">
        <table class="table">
            <thead>

                <tr>
                    <th>By Name: </th>
                    <th> <input name="SearchString" type="text" /></th>
                    <th>
                        <input type="submit" value="Search" class="btn btn-default" asp-action="Index" />
                    </th>
                    <th></th>
                    <th></th>
                    <th>By Mobile:</th>
                    <th><input name="searchNum" type="text" /></th>
                    <th>
                        <input type="submit" value="Search" class="btn btn-default" asp-action="Index2" />
                    </th>
                   
                </tr>
                <tr>
                    <th>By Name & Mobile:</th>
                    <th>
                        <input type="submit" value="SearchBoth" class="btn btn-default" asp-action="IndexBoth" />
                    </th>
                </tr>

            </thead>
        </table>

    </div>
</form>


<table class="table" style="background-color:cornsilk">
    <thead>

        <tr>
            <th>Name</th>
            <th>Mobile</th>
            <th>Date</th>
            <th>TimeSlotTitle</th>
            <th>TreatmentTitle</th>
            <th>IsDeleted</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var bookings in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Booking" asp-action="Details" asp-route-id="@bookings.BookingId"> @bookings.Name</a>

                </td>
                <td>
                    @bookings.Mobile

                </td>
                <td>
                    @bookings.BookedDate.Date.ToShortDateString()
                </td>
                <td>
                    @bookings.TimeSlots.TimeSlotTitle

                </td>
                <td>
                    @bookings.Treatments.TreatmentTitle
                </td>
                <td>
                    @bookings.IsDeleted
                </td>
                <td>
                    <a asp-controller="Booking" asp-action="Edit" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-primary" value="Edit" />

                        <i class="glyphicon glyphicon-pencil"></i>

                    </a>

                </td>

                <td>
                    <a asp-controller="Booking" asp-action="Details" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-info" value="Details" />
                        <i class="glyphicon glyphicon-user"></i>

                    </a>
                </td>

                <td>

                    <a asp-controller="Booking" asp-action="Delete" asp-route-id="@bookings.BookingId">

                        <input type="button" class="btn btn-danger" value="Delete" onclick="return confirm(' Are you sure you want to delete this item?');" />
                        <i class="glyphicon glyphicon-trash"></i>


                    </a>

                </td>
            </tr>
        }
    </tbody>
</table>